### ISSUE TITLE
issues with the plugin starting from version 4.15.5 of Strapi

### ISSUE THREAD

**Issue by abisewski** [notum-cz/strapi-plugin-record-locking#89]
When I updated Strapi to version 4.15.5, this error started appearing in the console when creating/editing a collection:

`main.cbea1cba.js:16167 TypeError: Cannot read properties of null (reading 'params')`

This makes it impossible to edit or create any collections.

![image](https://github.com/notum-cz/strapi-plugin-record-locking/assets/22551657/2640fee7-5610-4e5f-a388-bfdb0f62d929)

**Comment by omikulcik** [comment]
Hi @abisewski, this is caused by the newer versions of Strapi using `collectionType` instead of `collection-type`. I have just checked and the plugin works in the latest version. If you are using version that uses the old format of URL I suggest using older version of this plugin https://github.com/notum-cz/strapi-plugin-record-locking/releases/tag/v1.3.9
